import { describe, expect, it } from 'vitest';
import { jiraPomProperties } from '../../../src/bait/templates/jira-pom-properties.js';

const path =
  '/s/abc123def456/_/;/META-INF/maven/com.atlassian.jira/jira-webapp-dist/pom.properties';

const ctx = (method: string) => ({
  request: new Request(`http://example.test${path}`, { method }),
  path,
  category: 'cve-recon' as const,
  subcategory: 'atlassian-jira',
});

describe('jira-pom-properties', () => {
  it('returns a pom.properties body the Jira version-fingerprint scanner expects', async () => {
    const response = jiraPomProperties(ctx('GET'));
    expect(response.status).toBe(200);
    expect(response.headers.get('content-type')).toContain('text/plain');
    const body = await response.text();
    expect(body).toContain('#Generated by Maven');
    expect(body).toContain('groupId=com.atlassian.jira');
    expect(body).toContain('artifactId=jira-webapp-dist');
    expect(body).toMatch(/^version=\d+\.\d+\.\d+/m);
  });

  it('emits no canary / tracking headers', () => {
    const response = jiraPomProperties(ctx('GET'));
    for (const h of ['x-canary', 'x-honeypot', 'x-bait', 'x-trap']) {
      expect(response.headers.get(h)).toBeNull();
    }
  });
});
