import type { TemplateFn } from '../../types.js';

// Tier 1 decoy for Django's `settings.py`. Source disclosure exposes
// `SECRET_KEY` (used for session / CSRF / password-reset signing),
// the full `DATABASES['default']` block (DB host + creds), and any
// `EMAIL_HOST_PASSWORD` / cloud SDK keys the project may keep there.
// CWE-200 / CWE-538 disclosure class.
//
// We render the canonical Django startproject shape with placeholder
// values: `.invalid` DB host, `REDACTED_FOR_HONEYPOT` secrets,
// `DEBUG = False`, the default INSTALLED_APPS list.

const body = `"""
Django settings for example project.

Generated by 'django-admin startproject'.
"""

from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = 'REDACTED_FOR_HONEYPOT'
DEBUG = False
ALLOWED_HOSTS = ['app.example.invalid']

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'example',
        'USER': 'app_user',
        'PASSWORD': 'REDACTED_FOR_HONEYPOT',
        'HOST': 'db.example.invalid',
        'PORT': '5432',
    }
}

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.example.invalid'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'mailer@example.invalid'
EMAIL_HOST_PASSWORD = 'REDACTED_FOR_HONEYPOT'

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

STATIC_URL = 'static/'
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
`;

export const djangoSettings: TemplateFn = () => {
  return new Response(body, {
    status: 200,
    headers: { 'Content-Type': 'text/x-python; charset=UTF-8' },
  });
};
