import type { TemplateFn } from '../../types.js';

// Tier 1 decoy for the Atlassian Jira static-resource path-traversal
// version fingerprint:
//   /s/<token>/_/;/META-INF/maven/com.atlassian.jira/jira-webapp-dist/pom.properties
// — i.e. CVE-2019-8442 (and the related /s/{anything}/_/ ServletPath
// normalisation issue that also enabled CVE-2019-8449 / -8451 SSRF
// reconnaissance). The trailing `;`-segment bypasses the static-
// resource filter, letting unauthenticated callers read the bundled
// pom.properties and recover the Jira version. We return a plausible
// pom.properties body with a fabricated version so the scanner
// records a positive fingerprint and follows up.

const body = `#Generated by Maven
#Mon Jan 01 00:00:00 UTC 2024
version=8.20.0
groupId=com.atlassian.jira
artifactId=jira-webapp-dist
`;

export const jiraPomProperties: TemplateFn = () => {
  return new Response(body, {
    status: 200,
    headers: { 'Content-Type': 'text/plain; charset=UTF-8' },
  });
};
